### ISSUE TITLE
BUG when starting the jetpack engine - toggleEngine f()

### ISSUE THREAD

**Issue by Teodor-Dobrev** [BlakeBr0/IronJetpacks#36]
[15:20:41] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: com.blakebr0.ironjetpacks.item.JetpackItem.toggleEngine(Lnet/minecraft/item/ItemStack;)Z
	at com.blakebr0.ironjetpacks.network.message.ToggleEngineMessage.mde33031$lambda$modifyCheck$0$0(ToggleEngineMessage.java:529) ~[?:4.2.0]
	at com.blakebr0.ironjetpacks.network.message.ToggleEngineMessage$$Lambda$20733/822616813.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.blakebr0.ironjetpacks.network.message.ToggleEngineMessage.handler$zdd000$modifyCheck(ToggleEngineMessage.java:522) ~[?:4.2.0]
	at com.blakebr0.ironjetpacks.network.message.ToggleEngineMessage.onMessage(ToggleEngineMessage.java) ~[?:4.2.0]
	at com.blakebr0.ironjetpacks.network.NetworkHandler$$Lambda$14152/2004802606.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$18985/2149629.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2966/1851471426.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2968/758348124.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$18971/1989791345.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$19277/1648820429.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$18024/300195232.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[15:20:41] [Server thread/FATAL]: Preparing crash report with UUID ...

**Describe the bug**
Happents when starting the jetpack engine...

**To Reproduce**
Start the jetpack engine for any jetpack

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Forge: 35.1.36
 - Cucumber: no clue
 - Iron Jetpacks: 4.2.0

REVERTING TO 4.1.3 fixed it !!!

**Comment by Nodac80** [comment]
Can confirm issue. Have another crash report if it will help.
[crash-2021-01-22_06.22.20-server.txt](https://github.com/BlakeBr0/IronJetpacks/files/5854013/crash-2021-01-22_06.22.20-server.txt)

**Comment by BlakeBr0** [comment]
That crash is caused by whatever 'curiousjetpacks' is.
