### ISSUE TITLE
a crash on mohist server of ATM9

### ISSUE THREAD

**Issue by YusJade** [BlakeBr0/IronJetpacks#98]
**Describe the bug**
a crash on mohist server when i add this mod, it seems related to datapacks?
when i remove this mod, the server just work well.

**To Reproduce**
run the server of ATM9

**Expected behavior**
to start my ATM9 server which contains this mod.

**Screenshots / Scripts / Logs**
```
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:strap Expected: 24303 Got: 1255
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:basic_coil Expected: 24304 Got: 1256
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:advanced_coil Expected: 24305 Got: 1257
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:elite_coil Expected: 24306 Got: 1258
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:ultimate_coil Expected: 24307 Got: 1259
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:cell Expected: 24308 Got: 8696
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:thruster Expected: 24309 Got: 8697
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:capacitor Expected: 24310 Got: 8698
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:item: Object did not get ID it asked for. Name: ironjetpacks:jetpack Expected: 24311 Got: 8699
[15:51:56] [main/WARN] [net.minecraftforge.registries.ForgeRegistry]: Registry minecraft:sound_event: Object did not get ID it asked for. Name: ironjetpacks:jetpack Expected: 8662 Got: 10028
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/ERROR] [pneumaticcraft]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list
[15:51:59] [main/INFO] [GregTechCEu]: Registering dungeon loot...
[15:51:59] [main/INFO] [GregTechCEu]: GregTech Data loading took 2110ms
[15:51:59] [main/ERROR] [Cristel Lib]: Cristel Lib Config Pack has no data
[15:51:59] [main/WARN] [Cristel Lib]: T&T Waystone Patch Pack accepted!
[15:52:00] [main/INFO] [Supplementaries]: Generated runtime SERVER_DATA for pack Supplementaries Generated Pack (supplementaries) in: 207 ms
[15:52:00] [main/INFO] [Supplementaries]: Generated runtime SERVER_DATA for pack Supplementaries Generated Pack (supplementaries) in: 15 ms
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class com/mojang/blaze3d/vertex/PoseStack for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:01] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class com/lowdragmc/lowdraglib/client/scene/WorldSceneRenderer for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner]: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
[15:52:02] [main/INFO] [KubeJS]: Added bindings for script type SERVER from mod 'almostunified': [AlmostUnified]
[15:52:02] [main/INFO] [KubeJS Server]: example.js#5: Hello, World! (Loaded server scripts)
[15:52:02] [main/INFO] [KubeJS Server]: Loaded script server_scripts:example.js in 0.001 s
[15:52:02] [main/INFO] [KubeJS Server]: Loaded 1/1 KubeJS server scripts in 0.054 s with 0 errors and 0 warnings
[15:52:02] [main/INFO] [KubeJS Server]: Scripts loaded
[15:52:06] [main/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis]: Replaced 2 calls to Enchantment#getMaxLevel() in net/minecraft/server/commands/EnchantCommand
[15:52:07] [main/INFO] [FTB Ranks]: Loading command nodes...
[15:52:07] [main/INFO] [FTB Ranks]: Loaded 4186 command nodes
[15:52:07] [main/INFO] [zeta-internal]: Dispatching ForgeZAddReloadListener (as ZAddReloadListener) to 2 listeners
[15:52:07] [main/INFO] [quark-zeta]: Dispatching ForgeZAddReloadListener (as ZAddReloadListener) to 2 listeners
[15:52:07] [main/INFO] [quark-zeta]: Dispatching AdvancementModifierRegistry$1 (as ZGatherAdvancementModifiers) to 1 listener
[15:52:08] [Worker-Main-13/WARN] [artifacts.Artifacts]: Tag entries for curios:tags/items/magic_book.json cleared by tombstone-1.20.1-8.6.6.jar
[15:52:08] [Worker-Main-13/WARN] [AlmostUnified]: The following tags are invalid and will be ignored: [forge:gems/obsidian, forge:storage_blocks/potassium_nitrate, forge:ingots/coal_coke, forge:storage_blocks/raw_tungsten, forge:raw_materials/brass, forge:dusts/aeternium, forge:wires/enderium, forge:plates/coal, forge:gears/cobalt, forge:nuggets/sapphire, forge:gems/steel, forge:ingots/diamond, forge:nuggets/fluorite, forge:dusts/bitumen, forge:ores/charcoal, forge:rods/amber, forge:gears/fluorite, forge:raw_materials/elementium, forge:rods/obsidian, forge:gears/amber, forge:wires/diamond, forge:gears/aeternium, forge:gears/bitumen, forge:gems/amber, forge:storage_blocks/raw_potassium_nitrate, forge:dusts/chrome, forge:nuggets/mithril, forge:rods/cinnabar, forge:rods/sulfur, forge:storage_blocks/raw_aeternium, forge:raw_materials/fluorite, forge:nuggets/apatite, forge:dusts/elementium, forge:wires/zinc, forge:ores/steel, forge:plates/cinnabar, forge:storage_blocks/raw_invar, forge:raw_materials/aeternium, forge:ingots/lapis, forge:storage_blocks/raw_elementium, forge:gears/potassium_nitrate, forge:raw_materials/charcoal, forge:ores/bitumen, forge:wires/obsidian, forge:ores/potassium_nitrate, forge:gears/coal, forge:wires/brass, forge:wires/bronze, forge:wires/netherite, forge:nuggets/graphite, forge:storage_blocks/amber, forge:rods/potassium_nitrate, forge:gears/peridot, forge:raw_materials/lumium, forge:wires/aeternium, forge:wires/invar, forge:rods/fluorite, forge:wires/lapis, forge:nuggets/aeternium, forge:gems/zinc, forge:gems/tungsten, forge:raw_materials/steel, forge:gems/copper, forge:gems/brass, forge:gems/enderium, forge:storage_blocks/raw_obsidian, forge:gears/elementium, forge:nuggets/coal, forge:dusts/mithril, forge:gears/mithril, forge:storage_blocks/raw_bitumen, forge:storage_blocks/raw_signalum, forge:plates/graphite, forge:nuggets/lapis, forge:plates/mithril, forge:gems/aluminum, forge:ores/netherite, forge:ingots/peridot, forge:ingots/amber, forge:plates/sulfur, forge:gems/invar, forge:wires/tungsten, forge:wires/mithril, forge:ores/brass, forge:storage_blocks/mithril, forge:ingots/apatite, forge:plates/aeternium, forge:storage_blocks/chrome, forge:raw_materials/constantan, forge:raw_materials/invar, forge:gears/charcoal, forge:ingots/chrome, forge:ingots/aeternium, forge:raw_materials/chrome, forge:rods/elementium, forge:plates/bitumen, forge:wires/elementium, forge:rods/chrome, forge:nuggets/cinnabar, forge:wires/potassium_nitrate, forge:wires/tin, forge:storage_blocks/raw_electrum, forge:rods/aeternium, forge:nuggets/amber, forge:gems/tin, forge:ores/signalum, forge:wires/sulfur, forge:gears/obsidian, forge:wires/bitumen, forge:ores/invar, forge:gems/graphite, forge:gems/lead, forge:storage_blocks/raw_charcoal, forge:rods/charcoal, forge:gems/coal_coke, forge:ores/chrome, forge:gems/potassium_nitrate, forge:ingots/sapphire, forge:wires/signalum, forge:rods/bitumen, forge:ingots/emerald, forge:storage_blocks/raw_chrome, forge:gems/netherite, forge:gems/platinum, forge:storage_blocks/raw_fluorite, forge:gears/apatite, forge:wires/ruby, forge:wires/cobalt, forge:wires/amber, forge:storage_blocks/raw_brass, forge:wires/lumium, forge:raw_materials/bronze, forge:plates/chrome, forge:wires/graphite, forge:nuggets/peridot, forge:gems/lumium, forge:plates/fluorite, forge:ores/electrum, forge:rods/coal, forge:raw_materials/bitumen, forge:plates/elementium, forge:raw_materials/obsidian, forge:wires/constantan, forge:gears/coal_coke, forge:dusts/amber, forge:wires/osmium, forge:gems/iridium, forge:gems/uranium, forge:gems/cobalt, forge:gems/iron, forge:ores/bronze, forge:ores/enderium, forge:gems/signalum, forge:ores/mithril, forge:rods/netherite, forge:storage_blocks/raw_constantan, forge:ingots/potassium_nitrate, forge:ingots/sulfur, forge:wires/iridium, forge:storage_blocks/raw_mithril, forge:raw_materials/electrum, forge:storage_blocks/raw_bronze, forge:gems/chrome, forge:wires/peridot, forge:storage_blocks/raw_enderium, forge:ores/aeternium, forge:rods/mithril, forge:raw_materials/tungsten, forge:ores/obsidian, forge:wires/silver, forge:plates/amber, forge:raw_materials/amber, forge:wires/chrome, forge:nuggets/chrome, forge:raw_materials/coal_coke, forge:ingots/charcoal, forge:raw_materials/peridot, forge:ores/lumium, forge:ingots/fluorite, forge:nuggets/bitumen, forge:gears/chrome, forge:nuggets/ruby, forge:wires/uranium, forge:raw_materials/enderium, forge:ores/amber, forge:plates/coal_coke, forge:gears/graphite, forge:gems/bitumen, forge:wires/nickel, forge:gems/bronze, forge:ingots/coal, forge:ores/coal_coke, forge:raw_materials/mithril, forge:ores/tungsten, forge:storage_blocks/raw_coal_coke, forge:raw_materials/signalum, forge:wires/cinnabar, forge:gems/silver, forge:wires/charcoal, forge:storage_blocks/raw_lumium, forge:nuggets/charcoal, forge:wires/fluorite, forge:plates/potassium_nitrate, forge:gems/electrum, forge:plates/apatite, forge:nuggets/potassium_nitrate, forge:gears/cinnabar, forge:gems/aeternium, forge:ores/elementium, forge:wires/platinum, forge:plates/charcoal, forge:plates/peridot, forge:ingots/ruby, forge:gems/osmium, forge:storage_blocks/raw_steel, forge:wires/sapphire, forge:nuggets/coal_coke, forge:raw_materials/netherite, forge:wires/coal_coke, forge:gems/constantan, forge:wires/coal, forge:gems/mithril, forge:wires/apatite, forge:ingots/mithril, forge:raw_materials/potassium_nitrate, forge:ingots/cinnabar, forge:ores/constantan, forge:storage_blocks/aeternium, forge:rods/graphite, forge:rods/coal_coke, forge:nuggets/sulfur, forge:gems/elementium, forge:ingots/bitumen, forge:wires/emerald, forge:storage_blocks/raw_amber, forge:nuggets/obsidian, forge:gems/gold, forge:storage_blocks/raw_netherite, forge:gears/sulfur, forge:rods/peridot, forge:storage_blocks/raw_peridot, forge:gems/nickel]
[15:52:10] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/chests/bastion_other' into 'minecraft:chests/bastion_other'
[15:52:10] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/chests/nether_bridge' into 'minecraft:chests/nether_bridge'
[15:52:10] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/chests/ruined_portal' into 'minecraft:chests/ruined_portal'
[15:52:10] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/entities/cave_spider' into 'minecraft:entities/cave_spider'
[15:52:10] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/chests/bastion_bridge' into 'minecraft:chests/bastion_bridge'
[15:52:10] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/chests/bastion_treasure' into 'minecraft:chests/bastion_treasure'
[15:52:11] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/entities/spider' into 'minecraft:entities/spider'
[15:52:11] [Worker-Main-6/INFO] [Silent Gear]: Registered material modifier silentgear:grade
[15:52:11] [Worker-Main-6/INFO] [Silent Gear]: Registered material modifier silentgear:starcharged
[15:52:11] [Worker-Main-6/INFO] [Silent Gear]: Injecting loot table 'silentgear:inject/minecraft/entities/zombie_villager' into 'minecraft:entities/zombie_villager'
[15:52:11] [main/WARN] [net.minecraft.world.level.storage.loot.LootDataManager]: Datapack tried to redefine minecraft:empty loot table, ignoring
[15:52:11] [main/INFO] [placebo]: Registered 35 additional loot tables.
[15:52:11] [main/WARN] [AlmostUnified]: Recipe count: 93339
[15:52:14] [main/INFO] [com.cupboard.Cupboard]: Loaded config for: connectivity.json
[15:52:30] [main/WARN] [AlmostUnified]: Recipe count afterwards: 92698 (done in 18.76 s)
[15:52:30] [main/INFO] [Iron Jetpacks]: Loaded 14 jetpack type(s) in 3 ms
[15:52:30] [main/WARN] [net.minecraft.server.Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @3f3c966c; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @3f3c966c)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:250) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%23185!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%23185!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%23185!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23100!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23100!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23100!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23100!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23100!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23100!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23100!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at com.mohistmc.MohistMCStart.main(MohistMCStart.java:107) [mohist-1.20.1-595-server.jar:1.20.1-629]
Caused by: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @3f3c966c; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @3f3c966c)
	at com.blakebr0.cucumber.helper.RecipeHelper.fireRecipeManagerLoadedEvent(RecipeHelper.java:74) ~[Cucumber-1.20.1-7.0.8.jar%23693!/:7.0.8]
	at net.minecraft.world.item.crafting.RecipeManager.handler$cpg000$cucumber$apply(RecipeManager.java:6542) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:66) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:37) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	at net.minecraft.server.Main.main(Main.java:220) ~[server-1.20.1-20230612.114412-srg.jar%23998!/:?]
	... 16 more
```

**Versions (please complete the following information):**
 - Minecraft:  1.20.1
 - Forge: 47.2.10
 - Cucumber: 7.0.8
 - Iron Jetpacks: 7.0.6
 - Singleplayer or Multiplayer: Multiplayer (server)

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/Cucumber/issues/37
